### ISSUE TITLE
References to the Operating System are confusing.

### ISSUE THREAD

**Issue by jamesbeltonIBM** [ibm-cloud-docs/virtual-router-appliance#15]
This page talks about the 'latest Vyatta 5600 operating system', whereas the Recent Updates page (https://cloud.ibm.com/docs/infrastructure/virtual-router-appliance?topic=virtual-router-appliance-recent-updates-for-ibm-virtual-router-appliance#recent-updates-for-ibm-virtual-router-appliance) says "Version 18.x of the Brocade OS is now available for the Virtual Router Appliance."

It would be better to be consistent with the naming of the operating system.

**Comment by jbmitch** [comment]
Hey there @jamesbeltonIBM . When you say "this page", which topic are you referring to?

**Comment by jamesbeltonIBM** [comment]
Sorry, it would be this one: https://cloud.ibm.com/docs/infrastructure/virtual-router-appliance?topic=virtual-router-appliance-about-the-vra#about-the-vra

Overall, the documentation is a bit inconsistent with the way it names things - Vyatta 5600 is used in some places and 'Brocade vRouter 5600' or 'AT&T vRouter 5600' in others (e.g. on https://cloud.ibm.com/docs/infrastructure/virtual-router-appliance?topic=virtual-router-appliance-faqs-for-ibm-virtual-router-appliance#what-about-the-at-t-vrouter-5600-offering-)

I get the need to be transparent but I also wonder if we should even be referring to the underlying Vyatta / vRouter so much, given that the manufacturers have announced EoL / EoS on it and we are advocating that users migrate from the Vyatta 5400 because that too has gone EoL / EoS. Appreciate that we are still supporting it in the form of the VRA but from the point of view of the customer, it wouldn't make me feel too confident about migrating to the VRA if that too is based on a known EoL/EoS product. It might have the affect of me just wait for the next thing to come along, so that I don't have to migrate twice.....

**Comment by jbmitch** [comment]
Thanks, this is valuable input, @jamesbeltonIBM . I'll make the naming more consistent. As far as the migration stuff goes, you should bring that up up Stephen Laphen, Tony Rego, and Danielle Kingberg, who are dealing with and designing the migration experience to VRA from the 5400.

**Comment by jamesbeltonIBM** [comment]
Thanks, @jbmitch - will do.

**Comment by ibm-cos-help** [comment]
from Stephen:

Stephen Laphen [11:22 AM]
I agree that the changes naming due to changes in ownership are a source of confusion
The IBM Cloud offering is VRA...  the operating system is Vyatta 5600
We should state that AT&T is the vendor, but should reference Brocade as the prior vendor, since many users will still be familiar with that
