### ISSUE TITLE
Please keep only current supported version in TOC of AT&T Vyatta 5600 vRouter software patches

### ISSUE THREAD

**Issue by ka7harada** [ibm-cloud-docs/virtual-router-appliance#31]
Request:
Please remove remove 5.2 Rxx and keep only supported version (v18) in TOC and document body of AT&T Vyatta 5600 vRouter software patches. Since it states "This document lists the patches for the **currently supported** versions of the Vyatta Network OS 5600. "

TOC: sample of showing TOC still contains 5.2Rxx  
![image](https://user-images.githubusercontent.com/56877430/77336373-c2c6f080-6d6a-11ea-9d2e-441cef640d70.png)

**Link:**
https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-at-t-vyatta-5600-vrouter-software-patches&locale=en 

**Reason of this request:**
Current list of TOC does not match to the statement of IBM Doc as supported version.
IBM Cloud lifecycle page did not give customer clear explanation of EOS of VRA 's OS version, so please maintain the TOC and keep only supported version in it

**Comment by jbmitch** [comment]
Hi @ka7harada. I'm not sure what you're looking at or where the screenshot you provided came from, but when I look at the two TOCs (the main one on the left, and the topic one on the right) I don't see any references to 5.2 Rxx in the English version.

**Comment by ka7harada** [comment]
@jbmitch
This request relates to CMT AB5650 from premium customer.

To find 5.2 Rxx please try below 
TOC list: Scroll down the TOC list in right hand side and you will find many 5.2 in the list
Body of the page: Scroll down the page or Search the word "5.2" from body

**Comment by ka7harada** [comment]
how to search the word "5.2 Rxx" from Body of the page

Please search the term 5.2 in below page.
1. Open 
https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-at-t-vyatta-5600-vrouter-software-patches&locale=en#5-2R6S5
![image](https://user-images.githubusercontent.com/56877430/77365340-4d264900-6d99-11ea-94a8-a176f9e85574.png)

2.Search the word "5.2" from body on browser
![image](https://user-images.githubusercontent.com/56877430/77365522-9f676a00-6d99-11ea-8ae2-09c51c5ff0c2.png)

3.Repeat 2 till the search result reaches to the bottom
![image](https://user-images.githubusercontent.com/56877430/77365654-d89fda00-6d99-11ea-8a29-de23e0151956.png)

**Comment by ka7harada** [comment]
how to search the word "5.2 Rxx" from TOC on the right hand side

1.Open
https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-at-t-vyatta-5600-vrouter-software-patches&locale=en#5-2R6S5

![image](https://user-images.githubusercontent.com/56877430/77365922-44824280-6d9a-11ea-8f25-0cf9b5e66d69.png)

2.Scroll down the TOC list in right hand side and you will find many 5.2 in the list
![image](https://user-images.githubusercontent.com/56877430/77365961-5a900300-6d9a-11ea-9097-7e3923d4b389.png)

3.Repeat 2 till you reach to the bottom of TOC for finding  5.2 in the list

**Comment by ka7harada** [comment]
I'm afraid This request was closed without less investigation,
I uploaded additional explanation to search the word "5.2 R" 

This relates to urgent and critical case CS1721557/CMT＃AB5650 from 
Premium Customer 
https://github.com/ibm-cloud-docs/virtual-router-appliance/issues/31 

Could you please take care of this ASAP?
Thank you for your support


Best regards,
========================================
Kanako Harada
Technical Account Manager, Asia-Pacific 
IBM Watson and Cloud Platform
Phone : +81-050-3150-5873　
Email : kanah@jp.ibm.com
========================================
