### ISSUE TITLE
Please keep only current supported version in TOC an body of section for AT&T Vyatta 5600 vRouter software patches on IBM Cloud Doc

### ISSUE THREAD

**Issue by ka7harada** [ibm-cloud-docs/virtual-router-appliance#32]
**!! NOTE #31 was closed by misunderstanding. I could not reopen it so I created new one!!**
**"This is the request relates to  CMT AB5650"**
@jbmitch 

Request:
Please remove remove 5.2 Rxx and keep only supported version (v18) in TOC and document body of AT&T Vyatta 5600 vRouter software patches. Since it states "This document lists the patches for the **currently supported** versions of the Vyatta Network OS 5600. "

TOC: sample of showing TOC still contains 5.2Rxx  
![image](https://user-images.githubusercontent.com/56877430/77336373-c2c6f080-6d6a-11ea-9d2e-441cef640d70.png)

**Link:**
https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-at-t-vyatta-5600-vrouter-software-patches&locale=en 

**Reason of this request:**
Current list of TOC does not match to the statement of IBM Doc as supported version.
IBM Cloud lifecycle page did not give customer clear explanation of EOS of VRA 's OS version, so please maintain the TOC and keep only supported version in it

**Comment by ka7harada** [comment]
This request relates to CMT AB5650 from premium customer.
I'm afraid that you did not check entire page of the link.
Please re-open this request very soon and please take care of this.

To find 5.2 Rxx please try below
TOC list: Scroll down the TOC list in right hand side and you will find many 5.2 in the list
Body of the page: Scroll down the page or Search the word "5.2" from body

**Comment by ka7harada** [comment]
how to search the word "5.2 Rxx" from Body of the page

Please search the term 5.2 in below page.
1. Open 
https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-at-t-vyatta-5600-vrouter-software-patches&locale=en#5-2R6S5
![image](https://user-images.githubusercontent.com/56877430/77365340-4d264900-6d99-11ea-94a8-a176f9e85574.png)

2.Search the word "5.2" from body on browser
![image](https://user-images.githubusercontent.com/56877430/77365522-9f676a00-6d99-11ea-8ae2-09c51c5ff0c2.png)

3.Repeat 2 till the search result reaches to the bottom
![image](https://user-images.githubusercontent.com/56877430/77365654-d89fda00-6d99-11ea-8a29-de23e0151956.png)

**Comment by ka7harada** [comment]
how to search the word "5.2 Rxx" from TOC on the right hand side

1.Open
https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-at-t-vyatta-5600-vrouter-software-patches&locale=en#5-2R6S5

![image](https://user-images.githubusercontent.com/56877430/77365922-44824280-6d9a-11ea-8f25-0cf9b5e66d69.png)

2.Scroll down the TOC list in right hand side and you will find many 5.2 in the list
![image](https://user-images.githubusercontent.com/56877430/77365961-5a900300-6d9a-11ea-9097-7e3923d4b389.png)

3.Repeat 2 till you reach to the bottom of TOC for finding  5.2 in the list

**Comment by jbmitch** [comment]
@ka7harada I see what you're wanting now. Let me check with the OM on this, he is very involved in the format of this topic. I want to make sure he agrees with your request.

**Comment by ka7harada** [comment]
@jbmitch  thanks Much appreciate if you kindly reach to OM soon.
I've been working OM (Stephen) on this issue so if you reach to him he can understand the background of the request.

**Comment by ka7harada** [comment]
@jbmitch  I have meeting with customer today (JST) much appreciate if you kindly get approval of this request from OM so soon. Thank you for your support.

**Comment by ka7harada** [comment]
@slaphen  Stephen this is the IBM Doc revision request that I mentioned in Slack

This relates to CMT AB5650.
Much appreciate your quick action.

**Comment by jbmitch** [comment]
Sorry for the delay on this. The 5.2 references have been removed, and will be put into an archived topic at a later date. 

https://cloud.ibm.com/docs/infrastructure/virtual-router-appliance?topic=virtual-router-appliance-at-t-vyatta-5600-vrouter-software-patches

If you have any further issues with this one, you can contact me directly:  mitchell@us.ibm.com
