### ISSUE TITLE
Please update Japanese (ja) page for VRA lifecycle  according to English(en) page

### ISSUE THREAD

**Issue by ka7harada** [ibm-cloud-docs/virtual-router-appliance#35]
Japanese (ja) page for VRA lifecycle has **wrong EOS date**.
Please correct them according to English page.

**[Needs change]**
**Japanese version** of 
 [IBM Cloud Virtual Router Appliance 上の Vyatta ネットワーク・オペレーティング・システムのライフサイクル](https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-product-lifecycle-vyatta&locale=ja#latest-version-availability)

Please change date  2023 年 6 月 14 日 and  2023 年 12 月 14 日

オペレーティング・システム | コード名 | デビアン | DPDK | 保守サポート | サポート終了
-- | -- | -- | -- | -- | --
2012 | ハリファックス | 10 | 20.11 | **2023 年 6 月 14 日** | **2023 年 12 月 14 日**

**[Expected]**
**English version** of 
 [Lifecycle for Vyatta Network Operating System on the IBM Cloud Virtual Router Appliance](https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-product-lifecycle-vyatta&locale=en#latest-version-availability)
Operating system | Code name | Debian | DPDK | Maintenance Support | End of support
-- | -- | -- | -- | -- | --
2012 | Halifax | 10 | 20.11 | 14 Dec 2023 | 14 June 2024

**Comment by jbmitch** [comment]
This will automatically fix at the next translation refresh
